### PR TITLE
Upgrade tests and features

### PR DESCRIPTION
**Pull request by Firesphere**
Also updated to use `config` so the variables can be set in the yml file.

### CODE REVIEW

**Comment by Firesphere** [comment]
Need to have a check for the noscript support:
https://developers.google.com/recaptcha/docs/faq

**Comment by chillu** [comment]
Release notes:

```md
 * Use YML configuration (e.g. `Recaptcha.api_verify_server`) instead of `$js_options` class static
 * Removed `$useSSL` option (now always on SSL)
 * Removed `$valid_languages`, use `hl` parameter (see https://developers.google.com/recaptcha/docs/display)
 * Removed `$useAjaxAPI` (Recaptcha v2 works differently now)
 * `<noscript>` fallback requires additional configuration now (https://developers.google.com/recaptcha/docs/faq)
```

**Comment by chillu** [comment]
Thanks Ed and Simon! I'll let that stray last commit slide, but in general please try to squash and keep the commit messages relevant.

**Comment by Firesphere** [comment]
In general, I always do. But this one was (from my perspective) too funny to let it slide, that's why I didn't squash. (as per our Slack discussion ;) )

**Pull request merged**
