### PR TITLE
Update 2.0 branch to support SS3.7 and PHP 7.2

### PR DESCRIPTION
**Pull request by obj63mc**
This should allow people that are running 3.7 to use this module with PHP7.2.

https://docs.silverstripe.org/en/3/changelogs/3.7.0/

### CODE REVIEW

**Comment by thats4shaw** [comment]
Thanks @obj63mc.  I'm also keen to see this merged.

**Comment by ssmarco** [comment]
I would like to have this one as well :)

**Comment by michalkleiner** [comment]
@chillu would you mind looking at the PR, please?

**Comment by chillu** [comment]
Thanks!

**Pull request merged**
